//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\01-项目文档\03-执行项目\P15S020-NX-CSS-船舶软件系统\02-Implementation\01-DetailDesign\CCS_CAD_UI\Application\CCS_HUST_HFHZ_CAD_3_5_CombineCabin.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: chengdeng
//              Version: NX 10
//              Date: 02-27-2016  (Format: mm-dd-yyyy)
//              Time: 11:11
//
//==============================================================================

#ifndef CCS_HUST_HFHZ_CAD_3_5_COMBINECABIN_H_INCLUDED
#define CCS_HUST_HFHZ_CAD_3_5_COMBINECABIN_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>

//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport CCS_HUST_HFHZ_CAD_3_5_CombineCabin
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    CCS_HUST_HFHZ_CAD_3_5_CombineCabin();
    ~CCS_HUST_HFHZ_CAD_3_5_CombineCabin();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the CCS_HUST_HFHZ_CAD_3_5_CombineCabin.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* targetSelect;// Block type: Body Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* waitSelect;// Block type: Body Collector
    
};
#endif //CCS_HUST_HFHZ_CAD_3_5_COMBINECABIN_H_INCLUDED
